/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity.schema.json
export type SpacerSection = {
  _type: 'spacerSection';
  size?: 'small' | 'medium' | 'large' | 'section';
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type GallerySection = {
  _type: 'gallerySection';
  heading?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
    _key: string;
  }>;
};

export type FoundingMemberReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'foundingMember';
};

export type TeamGridSection = {
  _type: 'teamGridSection';
  heading?: string;
  member_filter?: Array<
    {
      _key: string;
    } & FoundingMemberReference
  >;
};

export type ProjectGridSection = {
  _type: 'projectGridSection';
  heading?: string;
  project_filter?: string;
  status_filter?: 'planning' | 'active' | 'completed';
};

export type FaqReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faq';
};

export type FaqListSection = {
  _type: 'faqListSection';
  heading?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
};

export type QuoteSection = {
  _type: 'quoteSection';
  quote?: string;
  attribution_name?: string;
  attribution_role?: string;
};

export type StatsRowSection = {
  _type: 'statsRowSection';
  items?: Array<{
    value?: string;
    label?: string;
    isYear?: boolean;
    _type: 'statItem';
    _key: string;
  }>;
};

export type NumberedListSection = {
  _type: 'numberedListSection';
  heading?: string;
  items?: Array<{
    number?: string;
    title?: string;
    description?: string;
    _type: 'numberedItem';
    _key: string;
  }>;
};

export type ImageCalloutSection = {
  _type: 'imageCalloutSection';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  caption?: string;
  side?: 'left' | 'right' | 'full';
};

export type RichTextSection = {
  _type: 'richTextSection';
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  twoColumn?: boolean;
};

export type CtaSection = {
  _type: 'ctaSection';
  heading?: string;
  body?: string;
  ctaLabel?: string;
};

export type StatsSection = {
  _type: 'statsSection';
  heading?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: 'stat';
    _key: string;
  }>;
};

export type MarqueeSection = {
  _type: 'marqueeSection';
  items?: Array<string>;
};

export type FoundingTeamSection = {
  _type: 'foundingTeamSection';
  heading?: string;
  subheading?: string;
};

export type CommitteesTeaserSection = {
  _type: 'committeesTeaserSection';
  heading?: string;
  subheading?: string;
};

export type ValuesSection = {
  _type: 'valuesSection';
  heading?: string;
  values?: Array<{
    title?: string;
    description?: string;
    _type: 'value';
    _key: string;
  }>;
};

export type MissionSection = {
  _type: 'missionSection';
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type HeroSection = {
  _type: 'heroSection';
  eyebrow?: string;
  headline?: string;
  subheadline?: string;
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  accentDark?: boolean;
};

export type Faq = {
  _id: string;
  _type: 'faq';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  category?: 'general' | 'application' | 'training' | 'committees';
  order?: number;
};

export type Event = {
  _id: string;
  _type: 'event';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  date?: string;
  location?: string;
  description?: string;
  type?: 'recruitment' | 'comp' | 'social' | 'speaker' | 'fair';
  external_url?: string;
};

export type CommitteeReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'committee';
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  summary?: string;
  narrative?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  committee?: CommitteeReference;
  status?: 'planning' | 'active' | 'completed';
  tags?: Array<string>;
  hero_image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'project';
};

export type Committee = {
  _id: string;
  _type: 'committee';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  director?: FoundingMemberReference;
  tagline?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  curriculum?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  signature_projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  comp_calendar?: Array<{
    name?: string;
    date?: string;
    url?: string;
    type?: 'recruitment' | 'comp' | 'social' | 'speaker';
    _type: 'compCalendarEntry';
    _key: string;
  }>;
  director_quote?: string;
  order?: number;
  accentColor?: 'gold' | 'navy';
};

export type FoundingMember = {
  _id: string;
  _type: 'foundingMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  role?: string;
  committee?:
    | 'wealth-management'
    | 'trading'
    | 'accounting-consulting'
    | 'investment-banking'
    | 'operations'
    | 'president';
  gradYear?: number;
  bio?: string;
  linkedinUrl?: string;
  photoReleaseObtained?: boolean;
  headshot?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  monogramOverride?: string;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seo_title?: string;
  seo_description?: string;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageCalloutSection)
    | ({
        _key: string;
      } & NumberedListSection)
    | ({
        _key: string;
      } & StatsRowSection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & FaqListSection)
    | ({
        _key: string;
      } & ProjectGridSection)
    | ({
        _key: string;
      } & TeamGridSection)
    | ({
        _key: string;
      } & MarqueeSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & CommitteesTeaserSection)
    | ({
        _key: string;
      } & CtaSection)
  >;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & MissionSection)
    | ({
        _key: string;
      } & ValuesSection)
    | ({
        _key: string;
      } & CommitteesTeaserSection)
    | ({
        _key: string;
      } & FoundingTeamSection)
    | ({
        _key: string;
      } & MarqueeSection)
    | ({
        _key: string;
      } & StatsSection)
    | ({
        _key: string;
      } & CtaSection)
  >;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ucla_compliant_name?: string;
  slogan?: string;
  mission_statement?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  disclaimer_text?: string;
  applyUrl?: string;
  clubEmail?: string;
  instagramUrl?: string;
  linkedinUrl?: string;
  slackInviteUrl?: string;
  domain_renewal_date?: string;
  brandName?: string;
  titleSuffix?: string;
  defaultMetaDescription?: string;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  foundedYear?: number;
  foundedTerm?: string;
  navLinks?: Array<{
    label?: string;
    href?: string;
    _type: 'navLink';
    _key: string;
  }>;
  organizationDescription?: string;
  sameAs?: Array<string>;
  errorCopy?: {
    notFoundHeading?: string;
    notFoundBody?: string;
    errorHeading?: string;
    errorBody?: string;
    loadingLabel?: string;
  };
  disclaimerText?: string;
  uclaCompliantName?: string;
  missionStatement?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  domainRenewalDate?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SpacerSection
  | SanityImageAssetReference
  | GallerySection
  | FoundingMemberReference
  | TeamGridSection
  | ProjectGridSection
  | FaqReference
  | FaqListSection
  | QuoteSection
  | StatsRowSection
  | NumberedListSection
  | ImageCalloutSection
  | RichTextSection
  | CtaSection
  | StatsSection
  | MarqueeSection
  | FoundingTeamSection
  | CommitteesTeaserSection
  | ValuesSection
  | MissionSection
  | HeroSection
  | Faq
  | Event
  | CommitteeReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | ProjectReference
  | Committee
  | FoundingMember
  | Page
  | HomePage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    ucla_compliant_name,    slogan,    mission_statement,    disclaimer_text,    applyUrl,    clubEmail,    instagramUrl,    linkedinUrl,    slackInviteUrl,    domain_renewal_date  }
export type SiteSettingsQueryResult = {
  ucla_compliant_name: string | null;
  slogan: string | null;
  mission_statement: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  disclaimer_text: string | null;
  applyUrl: string | null;
  clubEmail: string | null;
  instagramUrl: string | null;
  linkedinUrl: string | null;
  slackInviteUrl: string | null;
  domain_renewal_date: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0] {    title,    sections[] {      _key,      _type,      ...    }  }
export type HomePageQueryResult = {
  title: string | null;
  sections: Array<
    | {
        _key: string;
        _type: 'committeesTeaserSection';
        heading?: string;
        subheading?: string;
      }
    | {
        _key: string;
        _type: 'ctaSection';
        heading?: string;
        body?: string;
        ctaLabel?: string;
      }
    | {
        _key: string;
        _type: 'foundingTeamSection';
        heading?: string;
        subheading?: string;
      }
    | {
        _key: string;
        _type: 'heroSection';
        eyebrow?: string;
        headline?: string;
        subheadline?: string;
        primaryCtaLabel?: string;
        primaryCtaHref?: string;
        secondaryCtaLabel?: string;
        secondaryCtaHref?: string;
        accentDark?: boolean;
      }
    | {
        _key: string;
        _type: 'marqueeSection';
        items?: Array<string>;
      }
    | {
        _key: string;
        _type: 'missionSection';
        heading?: string;
        body?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?:
            | 'blockquote'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'normal';
          listItem?: 'bullet' | 'number';
          markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
          }>;
          level?: number;
          _type: 'block';
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: 'statsSection';
        heading?: string;
        stats?: Array<{
          value?: string;
          label?: string;
          _type: 'stat';
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: 'valuesSection';
        heading?: string;
        values?: Array<{
          title?: string;
          description?: string;
          _type: 'value';
          _key: string;
        }>;
      }
  > | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allCommitteesQuery
// Query: *[_type == "committee"] | order(order asc) {    _id,    name,    "slug": slug.current,    tagline,    description,    order,    accentColor,    "director": director-> {      _id,      firstName,      lastName,      role,      committee    }  }
export type AllCommitteesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  tagline: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  order: number | null;
  accentColor: 'gold' | 'navy' | null;
  director: {
    _id: string;
    firstName: string | null;
    lastName: string | null;
    role: string | null;
    committee:
      | 'accounting-consulting'
      | 'investment-banking'
      | 'operations'
      | 'president'
      | 'trading'
      | 'wealth-management'
      | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: allFoundingMembersQuery
// Query: *[_type == "foundingMember"] | order(lastName asc) {    _id,    firstName,    lastName,    role,    committee,    gradYear,    bio,    linkedinUrl,    photoReleaseObtained,    headshot,    monogramOverride  }
export type AllFoundingMembersQueryResult = Array<{
  _id: string;
  firstName: string | null;
  lastName: string | null;
  role: string | null;
  committee:
    | 'accounting-consulting'
    | 'investment-banking'
    | 'operations'
    | 'president'
    | 'trading'
    | 'wealth-management'
    | null;
  gradYear: number | null;
  bio: string | null;
  linkedinUrl: string | null;
  photoReleaseObtained: boolean | null;
  headshot: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  monogramOverride: string | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0] {\n    ucla_compliant_name,\n    slogan,\n    mission_statement,\n    disclaimer_text,\n    applyUrl,\n    clubEmail,\n    instagramUrl,\n    linkedinUrl,\n    slackInviteUrl,\n    domain_renewal_date\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "homePage"][0] {\n    title,\n    sections[] {\n      _key,\n      _type,\n      ...\n    }\n  }\n': HomePageQueryResult;
    '\n  *[_type == "committee"] | order(order asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    tagline,\n    description,\n    order,\n    accentColor,\n    "director": director-> {\n      _id,\n      firstName,\n      lastName,\n      role,\n      committee\n    }\n  }\n': AllCommitteesQueryResult;
    '\n  *[_type == "foundingMember"] | order(lastName asc) {\n    _id,\n    firstName,\n    lastName,\n    role,\n    committee,\n    gradYear,\n    bio,\n    linkedinUrl,\n    photoReleaseObtained,\n    headshot,\n    monogramOverride\n  }\n': AllFoundingMembersQueryResult;
  }
}
