/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity.schema.json
export type SpacerSection = {
  _type: 'spacerSection';
  size?: 'small' | 'medium' | 'large' | 'section';
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type GallerySection = {
  _type: 'gallerySection';
  heading?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
    _key: string;
  }>;
};

export type FoundingMemberReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'foundingMember';
};

export type TeamGridSection = {
  _type: 'teamGridSection';
  heading?: string;
  member_filter?: Array<
    {
      _key: string;
    } & FoundingMemberReference
  >;
};

export type ProjectGridSection = {
  _type: 'projectGridSection';
  heading?: string;
  project_filter?: string;
  status_filter?: 'planning' | 'active' | 'completed';
};

export type FaqReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faq';
};

export type FaqListSection = {
  _type: 'faqListSection';
  heading?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
};

export type QuoteSection = {
  _type: 'quoteSection';
  quote?: string;
  attribution_name?: string;
  attribution_role?: string;
};

export type StatsRowSection = {
  _type: 'statsRowSection';
  items?: Array<{
    value?: string;
    label?: string;
    isYear?: boolean;
    _type: 'statItem';
    _key: string;
  }>;
};

export type NumberedListSection = {
  _type: 'numberedListSection';
  heading?: string;
  items?: Array<{
    number?: string;
    title?: string;
    description?: string;
    _type: 'numberedItem';
    _key: string;
  }>;
};

export type ImageCalloutSection = {
  _type: 'imageCalloutSection';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  caption?: string;
  side?: 'left' | 'right' | 'full';
};

export type RichTextSection = {
  _type: 'richTextSection';
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  twoColumn?: boolean;
};

export type CtaSection = {
  _type: 'ctaSection';
  heading?: string;
  body?: string;
  ctaLabel?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
};

export type StatsSection = {
  _type: 'statsSection';
  heading?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: 'stat';
    _key: string;
  }>;
};

export type MarqueeSection = {
  _type: 'marqueeSection';
  items?: Array<string>;
};

export type FoundingTeamSection = {
  _type: 'foundingTeamSection';
  heading?: string;
  subheading?: string;
};

export type CommitteesTeaserSection = {
  _type: 'committeesTeaserSection';
  heading?: string;
  subheading?: string;
};

export type ValuesSection = {
  _type: 'valuesSection';
  heading?: string;
  values?: Array<{
    title?: string;
    description?: string;
    _type: 'value';
    _key: string;
  }>;
};

export type MissionSection = {
  _type: 'missionSection';
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type HeroSection = {
  _type: 'heroSection';
  eyebrow?: string;
  headline?: string;
  subheadline?: string;
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  accentDark?: boolean;
};

export type Faq = {
  _id: string;
  _type: 'faq';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  category?: 'general' | 'application' | 'training' | 'committees';
  order?: number;
};

export type CommitteeReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'committee';
};

export type Event = {
  _id: string;
  _type: 'event';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  date?: string;
  endDate?: string;
  location?: string;
  description?: string;
  type?: 'recruitment' | 'comp' | 'social' | 'speaker' | 'fair';
  status?: 'tbd' | 'scheduled' | 'past';
  external_url?: string;
  externalUrl?: string;
  committee?: CommitteeReference;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  summary?: string;
  narrative?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  committee?: CommitteeReference;
  status?: 'planning' | 'active' | 'completed';
  tags?: Array<string>;
  hero_image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'project';
};

export type Committee = {
  _id: string;
  _type: 'committee';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  director?: FoundingMemberReference;
  tagline?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  curriculum?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  signature_projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  comp_calendar?: Array<{
    name?: string;
    date?: string;
    url?: string;
    type?: 'recruitment' | 'comp' | 'social' | 'speaker';
    _type: 'compCalendarEntry';
    _key: string;
  }>;
  director_quote?: string;
  order?: number;
  accentColor?: 'gold' | 'navy';
  learn?: Array<string>;
  differentiator?: string;
  directorPlaceholder?: string;
  redirectsFrom?: Array<string>;
};

export type FoundingMember = {
  _id: string;
  _type: 'foundingMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  role?: string;
  committee?:
    | 'wealth-management'
    | 'trading'
    | 'accounting-consulting'
    | 'investment-banking'
    | 'operations'
    | 'president';
  gradYear?: number;
  bio?: string;
  linkedinUrl?: string;
  photoReleaseObtained?: boolean;
  headshot?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  monogramOverride?: string;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seo_title?: string;
  seo_description?: string;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageCalloutSection)
    | ({
        _key: string;
      } & NumberedListSection)
    | ({
        _key: string;
      } & StatsRowSection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & FaqListSection)
    | ({
        _key: string;
      } & ProjectGridSection)
    | ({
        _key: string;
      } & TeamGridSection)
    | ({
        _key: string;
      } & MarqueeSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & CommitteesTeaserSection)
    | ({
        _key: string;
      } & CtaSection)
  >;
};

export type CommitteesIndexPage = {
  _id: string;
  _type: 'committeesIndexPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
  hero?: {
    heading?: string;
    subheading?: string;
  };
  intro?: string;
  connectedByDesign?: {
    heading?: string;
    body?: string;
    paragraphs?: Array<string>;
  };
};

export type TeamPage = {
  _id: string;
  _type: 'teamPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
  hero?: {
    heading?: string;
    subheading?: string;
  };
  intro?: string;
  foundingClassHeading?: string;
  membersHeading?: string;
  membersPlaceholder?: string;
  alumniHeading?: string;
  alumniPlaceholder?: string;
};

export type ProjectsPage = {
  _id: string;
  _type: 'projectsPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
  hero?: {
    heading?: string;
    subheading?: string;
  };
  intro?: string;
  emptyState?: string;
  statusLegend?: Array<{
    status?: 'planning' | 'active' | 'completed';
    description?: string;
    _type: 'statusLegendEntry';
    _key: string;
  }>;
};

export type EventsPage = {
  _id: string;
  _type: 'eventsPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
  hero?: {
    heading?: string;
    subheading?: string;
  };
  intro?: string;
  upcomingEmptyState?: string;
  pastEmptyState?: string;
};

export type JoinPage = {
  _id: string;
  _type: 'joinPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
  hero?: {
    heading?: string;
    subheading?: string;
  };
  intro?: string;
  timeline?: Array<{
    stepNumber?: number;
    title?: string;
    body?: string;
    _type: 'timelineStep';
    _key: string;
  }>;
  applicationForm?: {
    heading?: string;
    body?: string;
    formUrl?: string;
  };
  faqs?: Array<{
    question?: string;
    answer?: string;
    _type: 'faq';
    _key: string;
  }>;
  eligibilityHeading?: string;
  eligibilityBullets?: Array<string>;
};

export type TrainingPage = {
  _id: string;
  _type: 'trainingPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
  hero?: {
    heading?: string;
    subheading?: string;
  };
  intro?: string;
  curriculum?: Array<{
    week?: string;
    topic?: string;
    body?: string;
    _type: 'curriculumEntry';
    _key: string;
  }>;
  programs?: Array<{
    name?: string;
    description?: string;
    format?: string;
    duration?: string;
    _type: 'program';
    _key: string;
  }>;
  signatureCertifications?: Array<{
    title?: string;
    body?: string;
    _type: 'certification';
    _key: string;
  }>;
};

export type AboutPage = {
  _id: string;
  _type: 'aboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
  hero?: {
    heading?: string;
    subheading?: string;
  };
  mission?: {
    heading?: string;
    body?: string;
  };
  history?: {
    heading?: string;
    body?: string;
  };
  signatureTrip?: {
    headline?: string;
    status?: string;
    body?: string;
    visible?: boolean;
  };
  values?: Array<{
    title?: string;
    body?: string;
    _type: 'value';
    _key: string;
  }>;
  sections?: Array<{
    heading?: string;
    body?: string;
    _type: 'section';
    _key: string;
  }>;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & MissionSection)
    | ({
        _key: string;
      } & ValuesSection)
    | ({
        _key: string;
      } & CommitteesTeaserSection)
    | ({
        _key: string;
      } & FoundingTeamSection)
    | ({
        _key: string;
      } & MarqueeSection)
    | ({
        _key: string;
      } & StatsSection)
    | ({
        _key: string;
      } & CtaSection)
  >;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ucla_compliant_name?: string;
  slogan?: string;
  mission_statement?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  disclaimer_text?: string;
  applyUrl?: string;
  clubEmail?: string;
  instagramUrl?: string;
  linkedinUrl?: string;
  slackInviteUrl?: string;
  domain_renewal_date?: string;
  brandName?: string;
  titleSuffix?: string;
  defaultMetaDescription?: string;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  foundedYear?: number;
  foundedTerm?: string;
  navLinks?: Array<{
    label?: string;
    href?: string;
    _type: 'navLink';
    _key: string;
  }>;
  organizationDescription?: string;
  sameAs?: Array<string>;
  errorCopy?: {
    notFoundHeading?: string;
    notFoundBody?: string;
    errorHeading?: string;
    errorBody?: string;
    loadingLabel?: string;
  };
  disclaimerText?: string;
  uclaCompliantName?: string;
  missionStatement?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  domainRenewalDate?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SpacerSection
  | SanityImageAssetReference
  | GallerySection
  | FoundingMemberReference
  | TeamGridSection
  | ProjectGridSection
  | FaqReference
  | FaqListSection
  | QuoteSection
  | StatsRowSection
  | NumberedListSection
  | ImageCalloutSection
  | RichTextSection
  | CtaSection
  | StatsSection
  | MarqueeSection
  | FoundingTeamSection
  | CommitteesTeaserSection
  | ValuesSection
  | MissionSection
  | HeroSection
  | Faq
  | CommitteeReference
  | Event
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | ProjectReference
  | Committee
  | FoundingMember
  | Page
  | CommitteesIndexPage
  | TeamPage
  | ProjectsPage
  | EventsPage
  | JoinPage
  | TrainingPage
  | AboutPage
  | HomePage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    brandName,    titleSuffix,    slogan,    "disclaimer": coalesce(disclaimerText, disclaimer_text),    "uclaName": coalesce(uclaCompliantName, ucla_compliant_name),    "mission": coalesce(missionStatement, mission_statement),    applyUrl,    clubEmail,    instagramUrl,    linkedinUrl,    slackInviteUrl,    navLinks,    foundedYear,    foundedTerm,    defaultMetaDescription,    defaultOgImage,    organizationDescription,    sameAs,    errorCopy,    "domainRenewal": coalesce(domainRenewalDate, domain_renewal_date)  }
export type SiteSettingsQueryResult = {
  brandName: string | null;
  titleSuffix: string | null;
  slogan: string | null;
  disclaimer: string | null;
  uclaName: string | null;
  mission: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  applyUrl: string | null;
  clubEmail: string | null;
  instagramUrl: string | null;
  linkedinUrl: string | null;
  slackInviteUrl: string | null;
  navLinks: Array<{
    label?: string;
    href?: string;
    _type: 'navLink';
    _key: string;
  }> | null;
  foundedYear: number | null;
  foundedTerm: string | null;
  defaultMetaDescription: string | null;
  defaultOgImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  organizationDescription: string | null;
  sameAs: Array<string> | null;
  errorCopy: {
    notFoundHeading?: string;
    notFoundBody?: string;
    errorHeading?: string;
    errorBody?: string;
    loadingLabel?: string;
  } | null;
  domainRenewal: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0] {    title,    sections[] {      _key,      _type,      ...    }  }
export type HomePageQueryResult = {
  title: string | null;
  sections: Array<
    | {
        _key: string;
        _type: 'committeesTeaserSection';
        heading?: string;
        subheading?: string;
      }
    | {
        _key: string;
        _type: 'ctaSection';
        heading?: string;
        body?: string;
        ctaLabel?: string;
        secondaryCtaLabel?: string;
        secondaryCtaHref?: string;
      }
    | {
        _key: string;
        _type: 'foundingTeamSection';
        heading?: string;
        subheading?: string;
      }
    | {
        _key: string;
        _type: 'heroSection';
        eyebrow?: string;
        headline?: string;
        subheadline?: string;
        primaryCtaLabel?: string;
        primaryCtaHref?: string;
        secondaryCtaLabel?: string;
        secondaryCtaHref?: string;
        accentDark?: boolean;
      }
    | {
        _key: string;
        _type: 'marqueeSection';
        items?: Array<string>;
      }
    | {
        _key: string;
        _type: 'missionSection';
        heading?: string;
        body?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?:
            | 'blockquote'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'normal';
          listItem?: 'bullet' | 'number';
          markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
          }>;
          level?: number;
          _type: 'block';
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: 'statsSection';
        heading?: string;
        stats?: Array<{
          value?: string;
          label?: string;
          _type: 'stat';
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: 'valuesSection';
        heading?: string;
        values?: Array<{
          title?: string;
          description?: string;
          _type: 'value';
          _key: string;
        }>;
      }
  > | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allCommitteesQuery
// Query: *[_type == "committee"] | order(order asc) {    _id,    name,    "slug": slug.current,    tagline,    description,    order,    accentColor,    "director": director-> {      _id,      firstName,      lastName,      role,      committee    }  }
export type AllCommitteesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  tagline: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  order: number | null;
  accentColor: 'gold' | 'navy' | null;
  director: {
    _id: string;
    firstName: string | null;
    lastName: string | null;
    role: string | null;
    committee:
      | 'accounting-consulting'
      | 'investment-banking'
      | 'operations'
      | 'president'
      | 'trading'
      | 'wealth-management'
      | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: sitemapCommitteesQuery
// Query: *[_type == "committee" && defined(slug.current)] | order(order asc) {    "slug": slug.current,    _updatedAt  }
export type SitemapCommitteesQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: allFoundingMembersQuery
// Query: *[_type == "foundingMember"] | order(lastName asc) {    _id,    firstName,    lastName,    role,    committee,    gradYear,    bio,    linkedinUrl,    photoReleaseObtained,    headshot,    monogramOverride  }
export type AllFoundingMembersQueryResult = Array<{
  _id: string;
  firstName: string | null;
  lastName: string | null;
  role: string | null;
  committee:
    | 'accounting-consulting'
    | 'investment-banking'
    | 'operations'
    | 'president'
    | 'trading'
    | 'wealth-management'
    | null;
  gradYear: number | null;
  bio: string | null;
  linkedinUrl: string | null;
  photoReleaseObtained: boolean | null;
  headshot: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  monogramOverride: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0] {    title,    seo,    hero,    mission,    history,    signatureTrip,    values,    sections  }
export type AboutPageQueryResult = {
  title: string | null;
  seo: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  } | null;
  hero: {
    heading?: string;
    subheading?: string;
  } | null;
  mission: {
    heading?: string;
    body?: string;
  } | null;
  history: {
    heading?: string;
    body?: string;
  } | null;
  signatureTrip: {
    headline?: string;
    status?: string;
    body?: string;
    visible?: boolean;
  } | null;
  values: Array<{
    title?: string;
    body?: string;
    _type: 'value';
    _key: string;
  }> | null;
  sections: Array<{
    heading?: string;
    body?: string;
    _type: 'section';
    _key: string;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: trainingPageQuery
// Query: *[_type == "trainingPage"][0] {    title,    seo,    hero,    intro,    curriculum,    programs,    signatureCertifications  }
export type TrainingPageQueryResult = {
  title: string | null;
  seo: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  } | null;
  hero: {
    heading?: string;
    subheading?: string;
  } | null;
  intro: string | null;
  curriculum: Array<{
    week?: string;
    topic?: string;
    body?: string;
    _type: 'curriculumEntry';
    _key: string;
  }> | null;
  programs: Array<{
    name?: string;
    description?: string;
    format?: string;
    duration?: string;
    _type: 'program';
    _key: string;
  }> | null;
  signatureCertifications: Array<{
    title?: string;
    body?: string;
    _type: 'certification';
    _key: string;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: joinPageQuery
// Query: *[_type == "joinPage"][0] {    title,    seo,    hero,    intro,    timeline,    applicationForm,    faqs,    eligibilityHeading,    eligibilityBullets  }
export type JoinPageQueryResult = {
  title: string | null;
  seo: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  } | null;
  hero: {
    heading?: string;
    subheading?: string;
  } | null;
  intro: string | null;
  timeline: Array<{
    stepNumber?: number;
    title?: string;
    body?: string;
    _type: 'timelineStep';
    _key: string;
  }> | null;
  applicationForm: {
    heading?: string;
    body?: string;
    formUrl?: string;
  } | null;
  faqs: Array<{
    question?: string;
    answer?: string;
    _type: 'faq';
    _key: string;
  }> | null;
  eligibilityHeading: string | null;
  eligibilityBullets: Array<string> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: eventsPageQuery
// Query: *[_type == "eventsPage"][0] {    title,    seo,    hero,    intro,    upcomingEmptyState,    pastEmptyState  }
export type EventsPageQueryResult = {
  title: string | null;
  seo: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  } | null;
  hero: {
    heading?: string;
    subheading?: string;
  } | null;
  intro: string | null;
  upcomingEmptyState: string | null;
  pastEmptyState: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allEventsQuery
// Query: *[_type == "event"] | order(date asc) {    _id,    name,    date,    endDate,    location,    description,    type,    status,    "externalUrl": coalesce(externalUrl, external_url),    "committee": committee->{ _id, name, "slug": slug.current }  }
export type AllEventsQueryResult = Array<{
  _id: string;
  name: string | null;
  date: string | null;
  endDate: string | null;
  location: string | null;
  description: string | null;
  type: 'comp' | 'fair' | 'recruitment' | 'social' | 'speaker' | null;
  status: 'past' | 'scheduled' | 'tbd' | null;
  externalUrl: string | null;
  committee: {
    _id: string;
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: projectsPageQuery
// Query: *[_type == "projectsPage"][0] {    title,    seo,    hero,    intro,    emptyState,    statusLegend  }
export type ProjectsPageQueryResult = {
  title: string | null;
  seo: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  } | null;
  hero: {
    heading?: string;
    subheading?: string;
  } | null;
  intro: string | null;
  emptyState: string | null;
  statusLegend: Array<{
    status?: 'active' | 'completed' | 'planning';
    description?: string;
    _type: 'statusLegendEntry';
    _key: string;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allProjectsQuery
// Query: *[_type == "project"] | order(_createdAt asc) {    _id,    name,    "slug": slug.current,    summary,    status,    tags,    "committee": committee->{ _id, name, "slug": slug.current }  }
export type AllProjectsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  summary: string | null;
  status: 'active' | 'completed' | 'planning' | null;
  tags: Array<string> | null;
  committee: {
    _id: string;
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: teamPageQuery
// Query: *[_type == "teamPage"][0] {    title,    seo,    hero,    intro,    foundingClassHeading,    membersHeading,    membersPlaceholder,    alumniHeading,    alumniPlaceholder  }
export type TeamPageQueryResult = {
  title: string | null;
  seo: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  } | null;
  hero: {
    heading?: string;
    subheading?: string;
  } | null;
  intro: string | null;
  foundingClassHeading: string | null;
  membersHeading: string | null;
  membersPlaceholder: string | null;
  alumniHeading: string | null;
  alumniPlaceholder: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: committeesIndexPageQuery
// Query: *[_type == "committeesIndexPage"][0] {    title,    seo,    hero,    intro,    connectedByDesign  }
export type CommitteesIndexPageQueryResult = {
  title: string | null;
  seo: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  } | null;
  hero: {
    heading?: string;
    subheading?: string;
  } | null;
  intro: string | null;
  connectedByDesign: {
    heading?: string;
    body?: string;
    paragraphs?: Array<string>;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allCommitteesIndexQuery
// Query: *[_type == "committee"] | order(order asc) {    _id,    name,    "slug": slug.current,    tagline,    learn,    accentColor,    order,    directorPlaceholder,    "director": director->{      firstName,      lastName,      role    }  }
export type AllCommitteesIndexQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  tagline: string | null;
  learn: Array<string> | null;
  accentColor: 'gold' | 'navy' | null;
  order: number | null;
  directorPlaceholder: string | null;
  director: {
    firstName: string | null;
    lastName: string | null;
    role: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: committeeBySlugQuery
// Query: *[_type == "committee" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    tagline,    description,    curriculum,    learn,    differentiator,    director_quote,    redirectsFrom,    accentColor,    order,    directorPlaceholder,    "director": director->{      _id,      firstName,      lastName,      role,      committee,      headshot,      photoReleaseObtained,      monogramOverride    },    "projects": signature_projects[]->{      _id,      name,      "slug": slug.current,      summary,      status    }  }
export type CommitteeBySlugQueryResult = {
  _id: string;
  name: string | null;
  slug: string | null;
  tagline: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  curriculum: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  learn: Array<string> | null;
  differentiator: string | null;
  director_quote: string | null;
  redirectsFrom: Array<string> | null;
  accentColor: 'gold' | 'navy' | null;
  order: number | null;
  directorPlaceholder: string | null;
  director: {
    _id: string;
    firstName: string | null;
    lastName: string | null;
    role: string | null;
    committee:
      | 'accounting-consulting'
      | 'investment-banking'
      | 'operations'
      | 'president'
      | 'trading'
      | 'wealth-management'
      | null;
    headshot: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    photoReleaseObtained: boolean | null;
    monogramOverride: string | null;
  } | null;
  projects: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    summary: string | null;
    status: 'active' | 'completed' | 'planning' | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: committeeSlugsQuery
// Query: *[_type == "committee" && defined(slug.current)] {    "slug": slug.current  }
export type CommitteeSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: committeeRedirectMapQuery
// Query: *[_type == "committee" && defined(slug.current)] {    "slug": slug.current,    redirectsFrom  }
export type CommitteeRedirectMapQueryResult = Array<{
  slug: string | null;
  redirectsFrom: Array<string> | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0] {\n    brandName,\n    titleSuffix,\n    slogan,\n    "disclaimer": coalesce(disclaimerText, disclaimer_text),\n    "uclaName": coalesce(uclaCompliantName, ucla_compliant_name),\n    "mission": coalesce(missionStatement, mission_statement),\n    applyUrl,\n    clubEmail,\n    instagramUrl,\n    linkedinUrl,\n    slackInviteUrl,\n    navLinks,\n    foundedYear,\n    foundedTerm,\n    defaultMetaDescription,\n    defaultOgImage,\n    organizationDescription,\n    sameAs,\n    errorCopy,\n    "domainRenewal": coalesce(domainRenewalDate, domain_renewal_date)\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "homePage"][0] {\n    title,\n    sections[] {\n      _key,\n      _type,\n      ...\n    }\n  }\n': HomePageQueryResult;
    '\n  *[_type == "committee"] | order(order asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    tagline,\n    description,\n    order,\n    accentColor,\n    "director": director-> {\n      _id,\n      firstName,\n      lastName,\n      role,\n      committee\n    }\n  }\n': AllCommitteesQueryResult;
    '\n  *[_type == "committee" && defined(slug.current)] | order(order asc) {\n    "slug": slug.current,\n    _updatedAt\n  }\n': SitemapCommitteesQueryResult;
    '\n  *[_type == "foundingMember"] | order(lastName asc) {\n    _id,\n    firstName,\n    lastName,\n    role,\n    committee,\n    gradYear,\n    bio,\n    linkedinUrl,\n    photoReleaseObtained,\n    headshot,\n    monogramOverride\n  }\n': AllFoundingMembersQueryResult;
    '\n  *[_type == "aboutPage"][0] {\n    title,\n    seo,\n    hero,\n    mission,\n    history,\n    signatureTrip,\n    values,\n    sections\n  }\n': AboutPageQueryResult;
    '\n  *[_type == "trainingPage"][0] {\n    title,\n    seo,\n    hero,\n    intro,\n    curriculum,\n    programs,\n    signatureCertifications\n  }\n': TrainingPageQueryResult;
    '\n  *[_type == "joinPage"][0] {\n    title,\n    seo,\n    hero,\n    intro,\n    timeline,\n    applicationForm,\n    faqs,\n    eligibilityHeading,\n    eligibilityBullets\n  }\n': JoinPageQueryResult;
    '\n  *[_type == "eventsPage"][0] {\n    title,\n    seo,\n    hero,\n    intro,\n    upcomingEmptyState,\n    pastEmptyState\n  }\n': EventsPageQueryResult;
    '\n  *[_type == "event"] | order(date asc) {\n    _id,\n    name,\n    date,\n    endDate,\n    location,\n    description,\n    type,\n    status,\n    "externalUrl": coalesce(externalUrl, external_url),\n    "committee": committee->{ _id, name, "slug": slug.current }\n  }\n': AllEventsQueryResult;
    '\n  *[_type == "projectsPage"][0] {\n    title,\n    seo,\n    hero,\n    intro,\n    emptyState,\n    statusLegend\n  }\n': ProjectsPageQueryResult;
    '\n  *[_type == "project"] | order(_createdAt asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    summary,\n    status,\n    tags,\n    "committee": committee->{ _id, name, "slug": slug.current }\n  }\n': AllProjectsQueryResult;
    '\n  *[_type == "teamPage"][0] {\n    title,\n    seo,\n    hero,\n    intro,\n    foundingClassHeading,\n    membersHeading,\n    membersPlaceholder,\n    alumniHeading,\n    alumniPlaceholder\n  }\n': TeamPageQueryResult;
    '\n  *[_type == "committeesIndexPage"][0] {\n    title,\n    seo,\n    hero,\n    intro,\n    connectedByDesign\n  }\n': CommitteesIndexPageQueryResult;
    '\n  *[_type == "committee"] | order(order asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    tagline,\n    learn,\n    accentColor,\n    order,\n    directorPlaceholder,\n    "director": director->{\n      firstName,\n      lastName,\n      role\n    }\n  }\n': AllCommitteesIndexQueryResult;
    '\n  *[_type == "committee" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    tagline,\n    description,\n    curriculum,\n    learn,\n    differentiator,\n    director_quote,\n    redirectsFrom,\n    accentColor,\n    order,\n    directorPlaceholder,\n    "director": director->{\n      _id,\n      firstName,\n      lastName,\n      role,\n      committee,\n      headshot,\n      photoReleaseObtained,\n      monogramOverride\n    },\n    "projects": signature_projects[]->{\n      _id,\n      name,\n      "slug": slug.current,\n      summary,\n      status\n    }\n  }\n': CommitteeBySlugQueryResult;
    '\n  *[_type == "committee" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': CommitteeSlugsQueryResult;
    '\n  *[_type == "committee" && defined(slug.current)] {\n    "slug": slug.current,\n    redirectsFrom\n  }\n': CommitteeRedirectMapQueryResult;
  }
}
